VAT shadow/src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('contrib/', include('contrib.urls')),
    path('asset/', include('asset_type.urls')),
    path('uploadasset/', include('upload_asset.urls')),
    path('roles/', include('roles.urls')),
    path('company/', include('company.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

VAT shadow/src/roles/urls.py
from django.urls import path
from .views import AddRoleView

urlpatterns = [path('add/', AddRoleView.as_view(), name='role_add')]

VAT shadow/src/roles/models.py
from django.db import models
from core.models import BaseModel
# Create your models here.


class PrivilageMaster(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)


class Role(BaseModel):
    ROLE_CHOICES = (( 'Admin', 'Admin'), ( 'Auditor', 'Auditor'))

    role_name = models.CharField(max_length=100)
    role_type = models.CharField(max_length=100, choices=ROLE_CHOICES)
    description = models.CharField(max_length=120, blank=True, null=True)

VAT shadow/src/roles/forms.py
from django import forms
from .models import Role


class RoleAddForm(forms.ModelForm):
    ROLE_CHOICES = (( 'Admin', 'Admin'), ( 'Auditor', 'Auditor'))
    role_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Type role name'}), max_length=100)
    role_type = forms.ChoiceField(widget=forms.RadioSelect, choices=ROLE_CHOICES)
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Type description',}), max_length=200)

    class Meta:
        model = Role
        fields = ['role_name', 'role_type', 'description']

VAT shadow/src/roles/views.py
from typing import Any, Dict
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import PrivilageMaster, Role
from .forms import RoleAddForm
from django.views.generic import CreateView

# Create your views here.


class AddRoleView(CreateView):
    model = Role
    template_name = 'roles/add.html'
    form_class = RoleAddForm

    def get_context_data(self, **kwargs):
        context = {}
        obj = PrivilageMaster.objects.all()
        context['obj'] = obj
        context['form'] = self.form_class
        return context

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

VAT shadow/src/templates/roles/add.html
{% extends 'contrib/base.html' %} {% load static %} {% block extrahead %}
<script src="{% static 'roles/js/add.js' %}"></script>
{% endblock extrahead %} {% block extrastyle %}
<link rel="stylesheet" href="{% static 'roles/css/add.css' %}" />
{% endblock extrastyle %} {% block contents %}
<div class="container-fluid wrapper">
  <div class="row">
    <div class="col">
      <p class="heading">Add Role</p>
    </div>
  </div>

  <div class="row role_form">
    <div class="col">
      <form action="" method="post">
        {% csrf_token %}
        <div class="formcontents">
          <div class="row firstrow">
            <div class="col-4">
              <div class="row">
                <label for="id_role_name">Role name:</label>
              </div>

              <input
                type="text"
                name="role_name"
                placeholder="Type role name"
                maxlength="100"
                required
                id="id_role_name"
              />
            </div>

            <div class="col">
              <label>Role type:</label>

              <div id="id_role_type">
                <div>
                  <label for="id_role_type_0"
                    ><input
                      type="radio"
                      name="role_type"
                      value="Admin"
                      required
                      id="id_role_type_0"
                    />
                    Admin</label
                  >
                </div>
                <div>
                  <label for="id_role_type_1"
                    ><input
                      type="radio"
                      name="role_type"
                      value="Auditor"
                      required
                      id="id_role_type_1"
                    />
                    Auditor</label
                  >
                </div>
              </div>
            </div>
          </div>

          <div class="row secondrow">
            <label for="id_description">Description:</label>

            <textarea
              name="description"
              cols="40"
              rows="10"
              placeholder="Type description"
              maxlength="200"
              required
              id="id_description"
            ></textarea>
          </div>
        </div>
      </form>
    </div>
  </div>

  <br />
  <div class="row">
    <div class="col">
      <p class="heading">Permission Details</p>
    </div>

    <div class="row">
      <div class="col">
        <div class="formcontents">
          {% for perm in obj %} {% if perm.name == "Verify Asset Task" %}
          <div class="row perm_row">
            <p>
              <input type="checkbox" name="" id="id_checkbox_perm" /> {{perm}}
            </p>
          </div>
          <br />
          {% elif perm.name == 'Initial Data Upload Access' %}
          <div class="row perm_row">
            <p>
              <input type="checkbox" name="" id="id_checkbox_perm" /> {{perm}}
            </p>
          </div>
          <br />
          {% elif perm.name == "Report Access" %}
          <div class="row perm_row">
            <p>
              <input
                type="checkbox"
                name=""
                class="{{perm.id}}"
                id="id_checkbox_perm"
              />
              {{perm}}
            </p>
          </div>
          <br />
          {% else %}
          <div class="row perm_row checkbox_row" id="{{perm.id}}">
            <div class="col">
              <p>
                <input
                  type="checkbox"
                  class="id_checkbox_perm"
                  name=""
                  id="id_checkbox_perm{{perm.id}}"
                />
                {{perm}}
              </p>
            </div>
            <div class="col checkbox_row" id="checkbox_row">
              <div class="div">
                <input
                  type="checkbox"
                  name="view"
                  class="id_checkbox_view"
                  id="view{{perm.id}}"
                />
                <label for="id_checkbox_view">View</label>
              </div>
              <div>
                <input
                  type="checkbox"
                  name="add"
                  class="id_checkbox_add"
                  id="add{{perm.id}}"
                />
                <label for="id_checkbox_add">Add</label>
              </div>
              <div>
                <input
                  type="checkbox"
                  name="edit"
                  class="id_checkbox_edit"
                  id="edit{{perm.id}}"
                />
                <label for="id_checkbox_edit">Edit</label>
              </div>
              <div>
                <input
                  type="checkbox"
                  name="delete"
                  class="id_checkbox_delete"
                  id="delete{{perm.id}}"
                />
                <label for="id_checkbox_delete">Delete</label>
              </div>
            </div>
          </div>
          <br />
          {% endif %} {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock contents %}